- name: Hello Play
  hosts: perdersi
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: python3

  tasks:
  - name: Distro Check
    fail:
      msg: 'Not fedora'
    when: ansible_facts['distribution'] != 'Fedora'
  - name: Packages
    dnf:
      name: ['python3', 'python3-libselinux', 'python3-virtualenv', 'selinux-policy-devel', 'policycoreutils-python-utils']
  - name: User
    user:
      name: psuser
      create_home: yes

  - name: Se
    block:
      - name: Se
        copy:
          src=sepol
          dest=/usr/local/perdersi/
      # FIXME: https://serverfault.com/questions/720598/execute-copy-and-set-only-if-something-changed/720602#720602
      - name: Se
        shell: make -C /usr/local/perdersi/sepol pspol.pp reload.stamp
      - name: Se
        shell: semodule -i pspol.pp
      - name: Se
        shell: _mkseuser.sh
	chdir: /usr/local/perdersi/sepol/
      - name: Se
        shell: _mkselogin.sh
        chdir: /usr/local/perdersi/sepol/
# shell: semanage login -a -s guest_u psuser
  - name: Venv
    block:
      - name: Venv Path
        file:
          path: /usr/local/perdersi
          state: directory
      - name: Venv Req
        copy: content="Flask>=1.0\nrequests2\npytest\npytest-cov\nGitPython"
          dest=/usr/local/perdersi/requirements.txt
      - name: Venv Create
        pip:
          requirements: /usr/local/perdersi/requirements.txt
          virtualenv: /usr/local/perdersi/venv
          virtualenv_command: virtualenv-3
