- name: General OS Setup
  hosts: perdersi
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: python3

  tasks:
  - name: Distro Check
    fail:
      msg: 'Not fedora'
    when: ansible_facts['distribution'] != 'Fedora'
  - name: Packages
    dnf:
      name:
        # dnf group, includes gcc, make, etc
        - "@C Development Tools and Libraries"
        - boost-devel
        - git
        - nginx
        - policycoreutils-python-utils
        - python3
        - python3-libselinux
        - python3-virtualenv
        - selinux-policy-devel
        - policycoreutils-python-utils
  - name: User
    user:
      name: psuser
      create_home: yes

  - name: Firewall
    block:
      - name: Many Secure Linux
        shell: |
          setsebool -P httpd_can_network_connect on
          semanage port -a -t http_port_t -p tcp 5200 || true
          semanage port -m -t http_port_t -p tcp 5200
          semanage port -a -t http_port_t -p tcp 5201 || true
          semanage port -m -t http_port_t -p tcp 5201
          semanage port -a -t http_port_t -p tcp 5202 || true
          semanage port -m -t http_port_t -p tcp 5202
      - name: Firewall Port
        shell: |
          firewall-cmd --permanent --add-service=http
          firewall-cmd --permanent --service=http --add-port=5200/tcp
          firewall-cmd --permanent --service=http --add-port=5201/tcp
          firewall-cmd --permanent --service=http --add-port=5202/tcp
      - name: Firewall Restart
        service:
          name=firewalld
          state=restarted
  - name: Nginx
    block:
      - name: Nginx Transfer
        synchronize:
          src=nginx
          dest=/usr/local/perdersi/
      - name: Nginx Copy Conf
        copy:
          src=nginx/ps_serv.conf
          dest=/etc/nginx/conf.d/ps_serv.conf
      - name: Nginx Apply Conf
        service:
          name=nginx
          state=restarted
  - name: Venv
    block:
      - name: Venv Path
        file:
          path: /usr/local/perdersi
          state: directory
      - name: Venv Req
        copy: content="Flask>=1.0\nrequests2\npytest\npytest-cov\nGitPython"
          dest=/usr/local/perdersi/requirements.txt
      - name: Venv Create (<29)
        pip:
          requirements: /usr/local/perdersi/requirements.txt
          virtualenv: /usr/local/perdersi/venv
          virtualenv_command: virtualenv-3
        when: ansible_facts['distribution_major_version'] < '29'
      - name: Venv Create (29+)
        pip:
          requirements: /usr/local/perdersi/requirements.txt
          virtualenv: /usr/local/perdersi/venv
          virtualenv_command: virtualenv
        when: ansible_facts['distribution_major_version'] >= '29'
