- name: Deploy
  hosts: perdersi
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: python3
    # SET EXTERNALLY: ps_cmake_binary_dir

  tasks:
  - name: Distro Check
    block:
      - fail:
          msg: 'Missing variable'
        when: ps_cmake_binary_dir is not defined
      - fail:
          msg: 'Not fedora'
        when: ansible_facts['distribution'] != 'Fedora'
  - name: Unarchive
    unarchive:
      src='{{ ps_cmake_binary_dir }}/coor.tar'
      dest='/usr/local/perdersi/deploy/unarchive'
  - name: Copy
    shell: |
      cp -f /usr/local/perdersi/deploy/unarchive/ps_coor.service    /etc/systemd/system/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_updater.service /etc/systemd/system/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_coor_starter.sh    /usr/local/bin/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_updater_starter.sh /usr/local/bin/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_config_deploy.py  /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_config_server.py  /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/ps_config_updater.py /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/coor.py        /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/timestamp.py   /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/server_coor.py /usr/local/perdersi/deploy/web/
      cp -f /usr/local/perdersi/deploy/unarchive/startup.py     /usr/local/perdersi/deploy/web/
  - name: Service Restart
    service:
      name=ps_coor.service
      daemon_reload=yes
      enabled=yes
      state=restarted
    with_items:
      - ps_coor.service
      - ps_updater.service
