- name: Deploy
  hosts: perdersi
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: python3
    # SET EXTERNALLY: ps_cmake_binary_dir

  tasks:
  - name: Distro Check
    block:
      - fail:
          msg: 'Missing variable'
        when: ps_cmake_binary_dir is not defined
      - fail:
          msg: 'Not fedora'
        when: ansible_facts['distribution'] != 'Fedora'
  - name: Deploy Files
    block:
      - shell: |
          rm -rf /usr/local/perdersi/deploy/unarchive
          mkdir  /usr/local/perdersi/deploy/unarchive
      - name: Unarchive
        unarchive:
          src: '{{ ps_cmake_binary_dir }}/coor.tar.gz'
          dest: '/usr/local/perdersi/deploy/unarchive'
          extra_opts:
            - --strip-components=1
      - name: Copy
        shell: |
          mkdir -p /usr/local/perdersi/web/
          cp -f /usr/local/perdersi/deploy/unarchive/*.service /etc/systemd/system/
          cp -f /usr/local/perdersi/deploy/unarchive/*.py /usr/local/perdersi/deploy/web/
  - name: Nginx Restart
    service:
      name: nginx
      daemon_reload: yes
      enabled: yes
      state: reloaded
  - name: Service Restart
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - ps_coor.service
      - ps_updater.service
