- name: Deploy
  hosts: perdersi
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: python3
    # SET EXTERNALLY: ps_cmake_binary_dir

  tasks:
  - name: Distro Check
    block:
      - fail:
          msg: 'Missing variable'
        when: ps_cmake_binary_dir is not defined
      - fail:
          msg: 'Not fedora'
        when: ansible_facts['distribution'] != 'Fedora'
  - name: Copy
    copy:
      src={{ item.src }}
      dest={{ item.dest }}
      mode={{ item.mode }}
    with_items:
      - { src: '../data/ps_coor.service', dest: '/etc/systemd/system/', mode: '0644' }
      - { src: '../data/ps_updater.service', dest: '/etc/systemd/system/', mode: '0644' }
      - { src: '../data/ps_coor_starter.sh', dest: '/usr/local/bin/', mode: '0755' }
      - { src: '../data/ps_updater_starter.sh', dest: '/usr/local/bin/', mode: '0755' }
      - { src: '{{ ps_cmake_binary_dir }}/ps_config_deploy.py', dest: '/usr/local/perdersi/deploy/web/', mode: '0644' }
      - { src: '{{ ps_cmake_binary_dir }}/ps_config_server.py', dest: '/usr/local/perdersi/deploy/web/', mode: '0644' }
      - { src: '../files/timestamp.py', dest: '/usr/local/perdersi/deploy/web/', mode: '0644' }
      - { src: '../files/server_coor.py', dest: '/usr/local/perdersi/deploy/web/', mode: '0644' }
      - { src: '../files/startup.py', dest: '/usr/local/perdersi/deploy/web/', mode: '0644' }
  - name: Service Restart
    service:
      name=ps_coor.service
      daemon_reload=yes
      enabled=yes
      state=restarted
    with_items:
      - ps_coor.service
      - ps_updater.service
