FIND_PATH(LIBGIT2_INCLUDE_DIR NAMES git2.h)

FIND_LIBRARY(LIBGIT2_LIBRARY NAMES git2)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibGit2 DEFAULT_MSG LIBGIT2_INCLUDE_DIR LIBGIT2_LIBRARY)

if(LIBGIT2_FOUND)
	add_library(LibGit2::LibGit2 UNKNOWN IMPORTED)
	set_target_properties(LibGit2::LibGit2 PROPERTIES
		IMPORTED_LOCATION "${LIBGIT2_LIBRARY}"
		INTERFACE_INCLUDE_DIRECTORIES "${LIBGIT2_INCLUDE_DIR}"
	)
endif()

MARK_AS_ADVANCED(LIBGIT2_INCLUDE_DIR LIBGIT2_LIBRARY)
